name: Upload coverage reports to Codecov

on:
  push:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run tests and collect coverage with JDK ${{ matrix.java }}
        run: mvn -B test
      - name: Upload coverage to Codecov with JDK ${{ matrix.java }}
        if: ${{ matrix.java == '8' }}
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
